### ISSUE TITLE
Feature 1: User can type by themselves

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can practice typing by themselves.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As soon as the user logins with their own account or as a guest, the home page will include the prompt that they can type for easy access.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="228" alt="Screen Shot 2022-02-14 at 1 06 41 PM" src="https://user-images.githubusercontent.com/59588689/153946600-02c7edd7-6af7-4731-9bbb-f224f0a78002.png">
<img width="228" alt="Screen Shot 2022-02-14 at 1 06 52 PM" src="https://user-images.githubusercontent.com/59588689/153946609-926421db-0c05-41b9-ac49-bdfd49b9e391.png">
<img width="206" alt="Screen Shot 2022-02-14 at 1 27 01 PM" src="https://user-images.githubusercontent.com/59588689/153949220-01879a18-4a07-4408-9a55-3d64b56288bb.png">

<img width="645" alt="Screen Shot 2022-02-14 at 1 07 14 PM" src="https://user-images.githubusercontent.com/59588689/153946620-1d96ed28-6640-4366-b996-6b2fe5e81f33.png">
<img width="644" alt="Screen Shot 2022-02-14 at 1 07 23 PM" src="https://user-images.githubusercontent.com/59588689/153946629-815924f0-e0e5-417e-982a-dfccce5725ae.png">
<img width="636" alt="Screen Shot 2022-02-14 at 1 27 10 PM" src="https://user-images.githubusercontent.com/59588689/153949232-a2f2acdb-de34-4e49-8f59-d5973a80485d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add quote data in 'database/data.sql'

### ☁️ Server

- [x] Update `server/index.js` to create a route, giving the client the quote prompt
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display quote prompt
- [x] Update component to highlight each character when pressed the correct key
- [x] Update component to highlight each character when pressed the incorrect key
- [ ] Shift prompt one line up when user reaches the third line of the prompt
- [x] Update blinker to be on the right of the current character

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
