### ISSUE TITLE
Feature 6: User can type with other users

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can type with other users.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user joins the room, the creator of the room can press the start button which will begin a countdown and the prompt.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-03 at 5 22 25 PM](https://user-images.githubusercontent.com/59588689/156681030-fe85cc81-c455-4c0b-8036-1a602300d689.png)
![Screen Shot 2022-03-03 at 5 22 43 PM](https://user-images.githubusercontent.com/59588689/156681058-8ad97921-1a63-4f01-a0b7-161afb8b8aa8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to send and receive the necessary data:
   - [ ] prompt
   - [ ] room creator
   - [ ] wpm
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to display prompt
- [ ] Create a consistent timer component to calculate wpm

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
