### ISSUE TITLE
Feature 7: User can see their progress live

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their progress live.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While the user is typing, a progress bar on the top half of the screen will progress the more they type.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-08 at 12 33 39 PM](https://user-images.githubusercontent.com/59588689/157320198-3a78b9ab-4493-4a23-b4b7-3075b7caa941.png)

![Screen Shot 2022-03-08 at 12 30 14 PM](https://user-images.githubusercontent.com/59588689/157319695-d0976394-5cdf-442a-ace3-808f1eb3dc04.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to listen for socket events that displays the user's progress bar
   - [ ] send each user's progress data to socket server
   - [ ] send each user's progress data back to the socket client
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to display the progress within the progress bar
- [ ] Update progress bar by number of correct words typed

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
