### ISSUE TITLE
Feature 8: User can reset the room

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can reset the room

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After pressing the start again button, the users will be able to type race again.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-08 at 3 51 02 PM](https://user-images.githubusercontent.com/59588689/157345391-ae193767-5bea-4d02-b625-d3ab439c1b63.png)
![Screen Shot 2022-03-08 at 3 51 15 PM](https://user-images.githubusercontent.com/59588689/157345413-8c9d9616-e559-4ba0-994e-1c150cc957bb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to request for a new prompt
- [ ] Update data model
   - [ ] set wpm to null
   - [ ] set wordsCompleted to 0
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to reset all of the users data
   - [ ] prompt
      - [ ] set this.state.startGame to false
   - [ ] user's words completed
      - [ ] set the value to 0
   - [ ] user's wpm
      - [ ] set the this.state.endTime and startTime to null
   - [ ] user's progress bar
      - [ ] set the value to 0

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
