### ISSUE TITLE
Feature 2: User can select duration of their typing session

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can time themselves as they type.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to select a duration when they type.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/59588689/154396579-8901cb8b-c38f-4224-a860-322be283c6b7.png)
![image](https://user-images.githubusercontent.com/59588689/154396607-5950337b-eff0-42f8-be82-f0dd9189ce9f.png)
![image](https://user-images.githubusercontent.com/59588689/154396643-0f524a49-7752-4b1b-aae4-e1866eeb5799.png)
![image](https://user-images.githubusercontent.com/59588689/154396674-85598fb1-cf5c-4dd2-8df2-b54f27bc458d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Add time duration options as part of the header
   - [x] selecting the option will highlight the time option and display on top of the prompt
- [x] Add a number on top of the prompt
- [x] Once user types, number will count down to 0

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
