### ISSUE TITLE
Feature 3: User can view their wpm

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their wpm.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user is done typing with the prompt or the countdown reaches zero, their wpm will show.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="240" alt="Screen Shot 2022-02-18 at 10 59 24 AM" src="https://user-images.githubusercontent.com/59588689/154745612-2b05dfaf-81dd-4c45-9265-d5877d28b923.png">
<img width="494" alt="Screen Shot 2022-02-18 at 10 59 41 AM" src="https://user-images.githubusercontent.com/59588689/154745619-4f0fa81d-b66e-41d5-a2a5-b5f36d9b0207.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to show a modal after the countdown or when the user finishes the prompt
   - [x] show wpm
   - [x] show a button that allows the user to reset the prompt

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
