### ISSUE TITLE
Feature 4: User can create a room 

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a room.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create a room that will allow other users to join the room.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-18 at 3 30 17 PM](https://user-images.githubusercontent.com/59588689/154774480-3c685142-4f4d-42b8-9065-f523a0a433be.png)
![Screen Shot 2022-02-18 at 3 30 33 PM](https://user-images.githubusercontent.com/59588689/154774504-b19e70d7-589e-428c-81f3-1703f93bafd7.png)
![Screen Shot 2022-02-18 at 3 31 38 PM](https://user-images.githubusercontent.com/59588689/154774590-ccbf4e5d-7135-42f4-8359-cc965ba3cd23.png)
![Screen Shot 2022-02-18 at 3 31 54 PM](https://user-images.githubusercontent.com/59588689/154774613-d24840be-d898-497a-8d4f-2cfbe131bbb1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] generate a unique identifier for room using socket.io
- [x] implement a create-room event 

### ⚡ Client

- [x] Create a footer component that contains the "create room" link
- [x] Create a "Room" page component
   - [ ] a modal pops out that displays the room's id
   - [ ] shows user's name with a progress bar
   - [ ] option to leave room
   - [ ] option to show id again

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
