### ISSUE TITLE
Feature 5: User can join a room

### ISSUE THREAD

**Issue by seankim248** [seankim248/typical-typer#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can join a room.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be prompted with a modal and the input for the room code to join.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-02-22 at 11 33 07 AM](https://user-images.githubusercontent.com/59588689/155205451-b93c5f61-2932-4652-90a7-ecaf90fae602.png)
![Screen Shot 2022-02-22 at 11 33 21 AM](https://user-images.githubusercontent.com/59588689/155205486-6b54f482-1537-4bba-80a7-54b86d45fafc.png)
![Screen Shot 2022-02-22 at 11 33 53 AM](https://user-images.githubusercontent.com/59588689/155205553-0e60d750-6c3d-4db2-9bb3-be9f5c0803a0.png)
![Screen Shot 2022-02-22 at 11 34 05 AM](https://user-images.githubusercontent.com/59588689/155205584-b4fe38f0-afbe-46a9-8828-d1bf1bff4869.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Bind the uuidv4 code to the room so that users will be able to copy paste the code to join the room
- [ ] listen for socket event when user joins the room
- [ ] listen for socket event when user leaves the room

### ⚡ Client

- [ ] Create a modal component that prompts the user to type in the room code.
- [ ] When the user joins the room, their name and a progress bar will show up under the creator's name and progress bar

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
